name = "foreverdoscrias"
author = "Biel"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b7301324f664d8765faca594b8aba4c0b858e5025073a953cc4a0462b70ca265"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
