name = "foreverdoscrias"
author = "Biel"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e7f54a7bf5dfe490e4af43624c1080354001828033943740afde28ce286dd1c2"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
