name = "foreverdoscrias"
author = "Biel"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "457d0b3b7405a82c999d9467d3ee93bf293f663d0bf887b2249f1ddd36da3829"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
